name: ci

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.trhiana}}
          password: ${{secrets.1631a179-1242-4421-b625-09d892b68690}}
      - 
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          image: python-helloworld
          tags: latest 
          platforms: linux/amd64, linux/arm64
          push: true